title: Calculador de Distribución de Carga
description: Diagrama de carga estática para la distribución de carga en vehículos de transporte terrestre
google_analytics: 
show_downloads: true
theme: jekyll-theme-architect

gems:
  - jekyll-mentions
