title: Calculador
description: Calculador de diagrama de carga estática para la distribución de carga en vehículos de transporte terrestre
google_analytics: 
show_downloads: false
theme: jekyll-theme-hacker
gems:
  - jekyll-mentions
